//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        public int Id { get; set; }
        public Nullable<int> PersonalDataId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string BVN { get; set; }
        public string AccountType { get; set; }
        public string EFT_ACC_Number { get; set; }
        public string EFT_Bank_Name { get; set; }
        public string OrderId { get; set; }
        public string BankDraft { get; set; }
        public string RegisterDate { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
    }
}
