//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuarantorFormUploading
    {
        public int Id { get; set; }
        public Nullable<int> GuarantorFormId { get; set; }
        public string ImageName { get; set; }
        public byte[] Images { get; set; }
        public string ImageStatus { get; set; }
        public string RegisterDate { get; set; }
        public Nullable<int> DeleteId { get; set; }
    
        public virtual GuarantorForm GuarantorForm { get; set; }
    }
}
