//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuarantorDetail
    {
        public int Id { get; set; }
        public Nullable<int> PersonalDataId { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string RegisterDate { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
    }
}
