//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a7d46_realtech01Entities : DbContext
    {
        public db_a7d46_realtech01Entities()
            : base("name=db_a7d46_realtech01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankDetail> BankDetails { get; set; }
        public virtual DbSet<DocumentUploading> DocumentUploadings { get; set; }
        public virtual DbSet<GuarantorDetail> GuarantorDetails { get; set; }
        public virtual DbSet<GuarantorDocumentDescription> GuarantorDocumentDescriptions { get; set; }
        public virtual DbSet<GuarantorForm> GuarantorForms { get; set; }
        public virtual DbSet<GuarantorFormUploading> GuarantorFormUploadings { get; set; }
        public virtual DbSet<LoanDetail> LoanDetails { get; set; }
        public virtual DbSet<LocalGovt> LocalGovts { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<OfficeAndIdentification> OfficeAndIdentifications { get; set; }
        public virtual DbSet<PaymentDeposit> PaymentDeposits { get; set; }
        public virtual DbSet<PersonalData> PersonalDatas { get; set; }
        public virtual DbSet<SignUp> SignUps { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UploadingDescription> UploadingDescriptions { get; set; }
    }
}
