//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeAndIdentification
    {
        public int Id { get; set; }
        public Nullable<int> PersonalDataId { get; set; }
        public string Employer { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficePhone { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> NetIncome { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string IdentificationName { get; set; }
        public string IdentificationNumber { get; set; }
        public string IssueDate { get; set; }
        public string ExpireDated { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public string Spouse { get; set; }
        public string DateRegister { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
    }
}
