//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDeposit
    {
        public int Id { get; set; }
        public Nullable<int> PersonalDataId { get; set; }
        public string LoanAmount { get; set; }
        public string LoanType { get; set; }
        public string FrequentlyPayment { get; set; }
        public Nullable<int> Instalment { get; set; }
        public string Interest { get; set; }
        public string Repayment { get; set; }
        public string PayableAmount { get; set; }
        public string BalanceAmount { get; set; }
        public string PaymentDate { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual PersonalData PersonalData { get; set; }
    }
}
