//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minpipWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalData()
        {
            this.BankDetails = new HashSet<BankDetail>();
            this.DocumentUploadings = new HashSet<DocumentUploading>();
            this.GuarantorDetails = new HashSet<GuarantorDetail>();
            this.LoanDetails = new HashSet<LoanDetail>();
            this.OfficeAndIdentifications = new HashSet<OfficeAndIdentification>();
            this.PaymentDeposits = new HashSet<PaymentDeposit>();
        }
    
        public int Id { get; set; }
        public string ApplicationNumber { get; set; }
        public int SignUp_Id { get; set; }
        public string ResidentialAddress { get; set; }
        public Nullable<int> LocalId { get; set; }
        public string ZipCode { get; set; }
        public string MobileNumber { get; set; }
        public string DOB { get; set; }
        public Nullable<int> OccupId { get; set; }
        public string DateRegister { get; set; }
        public int Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankDetail> BankDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentUploading> DocumentUploadings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuarantorDetail> GuarantorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanDetail> LoanDetails { get; set; }
        public virtual LocalGovt LocalGovt { get; set; }
        public virtual Occupation Occupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeAndIdentification> OfficeAndIdentifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDeposit> PaymentDeposits { get; set; }
        public virtual SignUp SignUp { get; set; }
    }
}
